//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JK_Exam.Entiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam_JK
    {
        public int ID { get; set; }
        public string Question { get; set; }
        public string ChooseA { get; set; }
        public string ChooseB { get; set; }
        public string ChooseC { get; set; }
        public string ChooseD { get; set; }
        public string Answer { get; set; }
        public string ChooseE { get; set; }
        public int QuestionType { get; set; }
    }
}
