//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JK_Exam.Entiy
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JK_ExamEntities : DbContext
    {
        public JK_ExamEntities()
            : base("name=JK_ExamEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Exam_JK> Exam_JK { get; set; }
        public virtual DbSet<Prize_JK> Prize_JK { get; set; }
        public virtual DbSet<User_JK> User_JK { get; set; }
    }
}
